In [4]:
import pandas

In [5]:
pandas.read_excel(io='internet_usage_spain.xlsx', sheet_name=1)

           name  internet_usage     sex  age    education  weight
0      Josefina               0  Female   66   Elementary      81
1         Vicki               1    Male   72   Elementary      78
2         David               1    Male   48   University      69
3        Curtis               0    Male   59          PhD     107
4     Josephine               1  Female   44          PhD      80
...         ...             ...     ...  ...          ...     ...
2450    Frances               1    Male   43   Elementary      94
2451      Harry               1  Female   18  High School      70
2452       Adam               0  Female   54   Elementary      60
2453  Christine               1    Male   31  High School      89
2454   Kimberly               0    Male   52   Elementary      88

[2455 rows x 6 columns]

In [6]:
pandas.read_excel(io='file_that_doesnt_exist.xlsx', sheet_name=1)

FileNotFoundError: [Errno 2] No such file or directory: 'file_that_doesnt_exist.xlsx'